-------------------------------------------------------------------------------
--  EllesmereUIDamageMeters.lua
--  Damage meter (Coming Soon). Placeholder; no runtime behavior yet.
-------------------------------------------------------------------------------
